// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGIRosCmpNxblc_oFBv-p-nJrR5MCd-T4',
    appId: '1:376921625457:web:b034447cc580e7edfa9cd0',
    messagingSenderId: '376921625457',
    projectId: 'dancekatta-218',
    authDomain: 'dancekatta-218.firebaseapp.com',
    storageBucket: 'dancekatta-218.firebasestorage.app',
    measurementId: 'G-TSHET44LTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQQKayq4PGWkyfOt3iBHe5NHx0CntJSM',
    appId: '1:376921625457:android:12b197cf02e72efdfa9cd0',
    messagingSenderId: '376921625457',
    projectId: 'dancekatta-218',
    storageBucket: 'dancekatta-218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTQbLgsHYnsKoqAK8juLcIyQGtQwR122Q',
    appId: '1:376921625457:ios:5de43323cc01640bfa9cd0',
    messagingSenderId: '376921625457',
    projectId: 'dancekatta-218',
    storageBucket: 'dancekatta-218.firebasestorage.app',
    androidClientId: '376921625457-2etjcc4cb0tn49s5o9mofinvbrciv1cf.apps.googleusercontent.com',
    iosClientId: '376921625457-rk1ogjfmft04bvu7fnv2c40na99ad2ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.dancekatta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTQbLgsHYnsKoqAK8juLcIyQGtQwR122Q',
    appId: '1:376921625457:ios:5de43323cc01640bfa9cd0',
    messagingSenderId: '376921625457',
    projectId: 'dancekatta-218',
    storageBucket: 'dancekatta-218.firebasestorage.app',
    androidClientId: '376921625457-2etjcc4cb0tn49s5o9mofinvbrciv1cf.apps.googleusercontent.com',
    iosClientId: '376921625457-rk1ogjfmft04bvu7fnv2c40na99ad2ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.dancekatta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGIRosCmpNxblc_oFBv-p-nJrR5MCd-T4',
    appId: '1:376921625457:web:f734e4581a96a7d0fa9cd0',
    messagingSenderId: '376921625457',
    projectId: 'dancekatta-218',
    authDomain: 'dancekatta-218.firebaseapp.com',
    storageBucket: 'dancekatta-218.firebasestorage.app',
    measurementId: 'G-HYJ1GTKSJR',
  );
}
