import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'screens/login_screen.dart';

import 'database/mongodb_connection.dart';
import 'screens/studio_registration_screen.dart';
import 'screens/home_screen.dart';
import 'models/user_model.dart';
import 'screens/splash_screen.dart';
import 'screens/studio_detail_screen.dart';
import 'models/studio_model.dart';
import 'screens/SignupScreenPart2.dart';
import 'screens/payment_demo_screen.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Connect to MongoDB (non-blocking now)
  try {
    MongoDBConnection.instance.connect(); // no await
  } catch (e) {
    debugPrint('❌ Failed to connect to MongoDB: $e');
  }

  runApp(const DanceKattaApp());
}

class DanceKattaApp extends StatelessWidget {
  const DanceKattaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dance Katta',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: const Color(0xFF3A5ED4),
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color.fromARGB(255, 249, 249, 250),
        ),
        useMaterial3: true,
        inputDecorationTheme: const InputDecorationTheme(
          border: OutlineInputBorder(),
          contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF3A5ED4),
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),
      ),
      routes: {
        '/home': (context) {
          final user = ModalRoute.of(context)!.settings.arguments as UserModel;
          return HomeScreen(user: user);
        },
        '/signupPart2': (context) {
          final user = ModalRoute.of(context)!.settings.arguments as UserModel;
          return SignupScreenPart2(
            firstName: user.firstName,
            lastName: user.lastName,
            email: user.email,
            mobile: user.mobile,
            altMobile: user.altMobile ?? '',
            dateOfBirth: user.dateOfBirth ?? '',
            guardianName: user.guardianName ?? '',
            guardianMobile: user.guardianMobile ?? '',
            guardianEmail: user.guardianEmail ?? '',
            address: user.address ?? '',
            city: user.city,
            state: user.state,
            country: user.country ?? '',
            pincode: user.pincode ?? '',
            profilePhoto: user.profilePhoto,
          );
        },
        '/studio-registration': (context) {
          final user = ModalRoute.of(context)!.settings.arguments as UserModel;
          return StudioRegistrationScreen(user: user);
        },
        '/studio-detail': (context) {
          final studio =
              ModalRoute.of(context)!.settings.arguments as StudioModel;
          return StudioDetailScreen(studio: studio);
        },
        '/payment-demo': (context) => const PaymentDemoScreen(),
      },
      home: const SplashScreen(),
    );
  }
}

/// ✅ Google Sign-In helper
Future<UserCredential?> signInWithGoogle() async {
  try {
    // Trigger the Google Sign-In flow
    final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();
    if (googleUser == null) return null; // User cancelled

    // Obtain auth details
    final GoogleSignInAuthentication googleAuth =
        await googleUser.authentication;

    // Create a credential
    final credential = GoogleAuthProvider.credential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

    // Sign in to Firebase
    return await FirebaseAuth.instance.signInWithCredential(credential);
  } catch (e) {
    debugPrint('❌ Google Sign-In failed: $e');
    return null;
  }
}
